# CI de Nível 01 - Disparo dentro do fluxo de CI de desenvolvimento
name: 'Execucao por push'
# triggers ou gatilhos de execucao
# Gatilho de execução por push ao repositorio
on: push

env:
    BROWSERSTACK_USERNAME: ${{ secrets.BS_USER }}
    BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}
    BROWSERSTACK_APP: ${{ vars.BS_APP }}
    LOJINHA_APP_PASS: ${{ secrets.LOJINHA_APP_PASS }}
    LOJINHA_APP_USER: ${{ secrets.LOJINHA_APP_USER }}

jobs:
  # - baixar as dependencias
  # - compilar
  # - testar

  wdioBrowserstack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes e2e Lojinha app
        run: |
              echo "BROWSERSTACK_USERNAME: $BROWSERSTACK_USERNAME"
              echo "BROWSERSTACK_ACCESS_KEY: $BROWSERSTACK_ACCESS_KEY"
              echo "BROWSERSTACK_APP: $BROWSERSTACK_APP"
              echo "LOJINHA_APP_PASS: $LOJINHA_APP_PASS"
              echo "LOJINHA_APP_USER: $LOJINHA_APP_USER"
              yarn run bs

      - uses: actions/upload-artifact@v4
        # por padrao a pipeline cancela se houver erro para evitar que ele cancele o passo seguinte no caso de erro, se quiser que a pipeline continue, basta adicionar o parametro 'if: ${{ !cancelled() }}'
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./report/android/bs
